version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: bbdd_tokenpass_admin       # El usuario de la base de datos
      POSTGRES_PASSWORD: frghu5&%G5&gf   # La contraseña del usuario
      POSTGRES_DB: bbdd_tokenpass  # Nombre de la base de datos
    ports:
      - "5432:5432"  # Exponer el puerto para acceder a la base de datos
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Para persistir datos en tu máquina local

volumes:
  postgres_data:
